services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "512M"